<a href="https://colab.research.google.com/github/Nolan-Jgr/golf-analytics-project/blob/main/notebooks/01_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Golf Analytics Project
## Phase 1: Data Cleaning & Preparation

**Author:** Nolan Jaeger  
**Dataset:** Fictional Golf Performance Dataset  
**Records:** 25,000  
**Tools:** Python, Pandas, Google Colab

### Project Objective

The objective of this project is to analyze fictional golf performance data
to identify factors associated with player performance, tournament outcomes,
and earnings.

This first phase focuses on inspecting, cleaning, validating, and preparing
the dataset for further analysis.

### Phase 1 Overview
This notebook prepares the fictional golf performance dataset for exploratory analysis, SQL analysis, dashboard development, and predictive modeling.

The primary goals of this phase are to:

Inspect the structure of the dataset
Identify missing values and duplicate records
Verify data types and ranges
Validate player and tournament information
Create additional analytical variables
Perform a final data quality check
Export a cleaned dataset for later phases

### Import Libraries

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

### Load Dataset

The dataset contains 25,000 fictional golf performance records.

The raw dataset will be loaded into a Pandas DataFrame for inspection and
cleaning.

In [3]:
df = pd.read_csv("/content/drive/MyDrive/Fictional_Golf_Project/Data/Fictional_Golf_Dataset_25000_Realistic.csv")

,PlayerID,FirstName,LastName,Age,Tournament,Course,Season,Round,Date,CoursePar,DriveDistance,FairwaysHit,GIR,Putts,Birdies,Bogeys,Score,StrokesGainedTotal,Earnings,ScoreToPar,BirdiePct,BogeyPct,EarningsPerStroke
0,218,Ethan,Jackson,35,Highland Invitational,Highland National,2025,1,2025-04-12,70,283.2,10,14,31,4,4,73,-0.43,17602.99,3,0.2222,0.2222,241.14
1,452,Tyler,Brown,35,Lakeview Championship,Lakeview Resort,2025,4,2025-04-01,72,312.0,12,14,28,9,4,68,1.54,10919.02,-4,0.5000,0.2222,160.57
2,418,Ethan,Smith,25,Cedar Hills Classic,Cedar Hills Golf Club,2025,1,2025-04-26,71,300.6,8,12,35,5,5,68,-0.29,16697.88,-3,0.2778,0.2778,245.56
3,411,Ryan,Smith,20,Riverbend Open,Riverbend Country Club,2025,1,2025-05-24,71,286.0,7,11,31,6,1,67,-0.04,17070.76,-4,0.3333,0.0556,254.79
4,5,Cameron,Smith,26,Mountain Invitational,Mountain Creek,2025,3,2025-06-09,72,265.0,9,13,31,5,3,73,0.71,8371.10,1,0.2778,0.1667,114.67

In [4]:
df.head()

,PlayerID,FirstName,LastName,Age,Tournament,Course,Season,Round,Date,CoursePar,DriveDistance,FairwaysHit,GIR,Putts,Birdies,Bogeys,Score,StrokesGainedTotal,Earnings,ScoreToPar,BirdiePct,BogeyPct,EarningsPerStroke
0,218,Ethan,Jackson,35,Highland Invitational,Highland National,2025,1,2025-04-12,70,283.2,10,14,31,4,4,73,-0.43,17602.99,3,0.2222,0.2222,241.14
1,452,Tyler,Brown,35,Lakeview Championship,Lakeview Resort,2025,4,2025-04-01,72,312.0,12,14,28,9,4,68,1.54,10919.02,-4,0.5000,0.2222,160.57
2,418,Ethan,Smith,25,Cedar Hills Classic,Cedar Hills Golf Club,2025,1,2025-04-26,71,300.6,8,12,35,5,5,68,-0.29,16697.88,-3,0.2778,0.2778,245.56
3,411,Ryan,Smith,20,Riverbend Open,Riverbend Country Club,2025,1,2025-05-24,71,286.0,7,11,31,6,1,67,-0.04,17070.76,-4,0.3333,0.0556,254.79
4,5,Cameron,Smith,26,Mountain Invitational,Mountain Creek,2025,3,2025-06-09,72,265.0,9,13,31,5,3,73,0.71,8371.10,1,0.2778,0.1667,114.67

In [5]:
df.tail()

,PlayerID,FirstName,LastName,Age,Tournament,Course,Season,Round,Date,CoursePar,DriveDistance,FairwaysHit,GIR,Putts,Birdies,Bogeys,Score,StrokesGainedTotal,Earnings,ScoreToPar,BirdiePct,BogeyPct,EarningsPerStroke
24995,394,Blake,Lewis,41,Southern Classic,Southern Pines,2025,4,2025-07-22,71,313.1,9,12,29,5,0,68,1.92,20427.32,-3,0.2778,0.0000,300.40
24996,348,Sam,Robinson,45,Lakeview Championship,Lakeview Resort,2025,3,2025-03-31,72,256.4,10,14,34,4,5,72,-1.34,7250.46,0,0.2222,0.2778,100.70
24997,216,Parker,Jackson,42,Pine Ridge Classic,Pine Ridge Golf Club,2025,1,2025-03-01,72,305.8,10,13,33,4,1,69,0.80,26813.09,-3,0.2222,0.0556,388.60
24998,449,Chris,Brown,36,Mountain Invitational,Mountain Creek,2025,4,2025-06-10,72,292.4,7,12,34,3,3,79,-1.40,3355.54,7,0.1667,0.1667,42.48
24999,414,Blake,Smith,25,Champions Cup,Champions National,2025,3,2025-08-04,72,302.5,10,15,32,3,4,68,2.77,24734.67,-4,0.1667,0.2222,363.75

### Dataset Dimensions

In [6]:
df.shape

(25000, 23)

The dataset contains 25,000 observations and 23 variables. Each observation
represents a round-level golf performance record containing player,
tournament, scoring, performance, and financial information.

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   PlayerID            25000 non-null  int64
 1   FirstName           25000 non-null  object
 2   LastName            25000 non-null  object
 3   Age                 25000 non-null  int64
 4   Tournament          25000 non-null  object
 5   Course              25000 non-null  object
 6   Season              25000 non-null  int64
 7   Round               25000 non-null  int64
 8   Date                25000 non-null  object
 9   CoursePar           25000 non-null  int64
 10  DriveDistance       25000 non-null  float64
 11  FairwaysHit         25000 non-null  int64
 12  GIR                 25000 non-null  int64
 13  Putts               25000 non-null  int64
 14  Birdies             25000 non-null  int64
 15  Bogeys              25000 non-null  int64
 16  Score               25000 non-null  int64
 17  StrokesGainedTotal  25000 non-null  float64
 18  Earnings            25000 non-null  float64
 19  ScoreToPar          25000 non-null  int64
 20  BirdiePct           25000 non-null  float64
 21  BogeyPct            25000 non-null  float64
 22  EarningsPerStroke   25000 non-null  float64
dtypes: float64(6), int64(12), object(5)
memory usage: 4.4+ MB

### Data Quality Assessment

#### Missing Value(s)

In [8]:
df.isnull().sum()

PlayerID              0
FirstName             0
LastName              0
Age                   0
Tournament            0
Course                0
Season                0
Round                 0
Date                  0
CoursePar             0
DriveDistance         0
FairwaysHit           0
GIR                   0
Putts                 0
Birdies               0
Bogeys                0
Score                 0
StrokesGainedTotal    0
Earnings              0
ScoreToPar            0
BirdiePct             0
BogeyPct              0
EarningsPerStroke     0
dtype: int64

In [9]:
df.isnull().sum().sum()

np.int64(0)

The dataset was checked for missing values across all variables. No missing
values were identified, allowing the analysis to proceed without requiring
imputation or row removal.

#### Duplicate Records

In [10]:
df.duplicated().sum()

np.int64(0)

The dataset was checked for completely duplicated records. No duplicate rows
were identified.

#### Unique Values

In [11]:
df.nunique()

PlayerID                500
FirstName                20
LastName                 20
Age                      28
Tournament               12
Course                   12
Season                    1
Round                     4
Date                     48
CoursePar                 3
DriveDistance          1057
FairwaysHit              11
GIR                      13
Putts                    16
Birdies                  11
Bogeys                    8
Score                    26
StrokesGainedTotal      931
Earnings              23790
ScoreToPar               26
BirdiePct                11
BogeyPct                  8
EarningsPerStroke     17206
dtype: int64

#### Validate Player Identities

In [13]:
df.groupby("PlayerID")["FirstName"].nunique().max()

1

In [14]:
df.groupby("PlayerID")["LastName"].nunique().max()

1

Every PlayerID has one consistent first name and one consistent last name.

In [15]:
df.groupby("PlayerID").size().describe()

count    500.000000
mean      50.000000
std        1.402831
min       48.000000
25%       49.000000
50%       50.000000
75%       51.000000
max       55.000000
dtype: float64

#### Verify Player-Level Grouping

In [17]:
player_check = (
    df.groupby(["PlayerID","FirstName","LastName"])["Score"]
    .agg(["count","mean","min","max"])
    .sort_values("mean")
)
player_check.head(10)

                             count       mean  min  max
PlayerID FirstName LastName
479      Mason     Davis        52  64.269231   60   69
253      Logan     Harris       49  64.734694   60   72
210      Jamie     Jackson      50  64.880000   60   72
221      Alex      White        53  64.886792   60   69
180      Luke      Anderson     52  65.153846   60   70
114      Blake     Wilson       51  65.176471   61   70
126      Drew      Moore        50  65.220000   60   69
379      Mason     Clark        50  65.320000   60   71
285      Cameron   Thompson     51  65.647059   60   73
421      Alex      Johnson      51  65.764706   60   73

#### Descriptive Statistics

In [18]:
df.describe()

,PlayerID,Age,Season,Round,CoursePar,DriveDistance,FairwaysHit,GIR,Putts,Birdies,Bogeys,Score,StrokesGainedTotal,Earnings,ScoreToPar,BirdiePct,BogeyPct,EarningsPerStroke
count,25000.000000,25000.000000,25000.0,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.00000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,250.297440,31.111720,2025.0,2.504880,71.333480,295.246208,8.993000,12.012480,30.00004,4.022440,3.000600,71.529400,-0.000503,11646.325822,0.195920,0.223472,0.166708,166.986734
std,144.337087,8.108619,0.0,1.118046,0.744992,17.780500,2.292047,2.379057,2.58814,1.976546,1.533354,3.622703,1.593461,6499.214142,3.556723,0.109799,0.085179,98.995926
min,1.000000,18.000000,2025.0,1.000000,70.000000,225.000000,4.000000,6.000000,23.00000,0.000000,0.000000,60.000000,-5.000000,0.000000,-12.000000,0.000000,0.000000,0.000000
25%,125.000000,24.000000,2025.0,2.000000,71.000000,283.200000,7.000000,10.000000,28.00000,3.000000,2.000000,69.000000,-1.080000,6931.352500,-2.000000,0.166700,0.111100,94.380000
50%,250.000000,31.000000,2025.0,3.000000,71.000000,295.200000,9.000000,12.000000,30.00000,4.000000,3.000000,72.000000,-0.000000,11545.855000,0.000000,0.222200,0.166700,161.295000
75%,375.000000,38.000000,2025.0,4.000000,72.000000,307.200000,11.000000,14.000000,32.00000,5.000000,4.000000,74.000000,1.070000,16064.747500,3.000000,0.277800,0.222200,231.252500
max,500.000000,45.000000,2025.0,4.000000,72.000000,371.900000,14.000000,18.000000,38.00000,10.000000,7.000000,85.000000,5.000000,35555.350000,13.000000,0.555600,0.388900,582.850000

In [19]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
PlayerID,25000.0,250.297440,144.337087,1.0,125.0000,250.0000,375.0000,500.0000
Age,25000.0,31.111720,8.108619,18.0,24.0000,31.0000,38.0000,45.0000
Season,25000.0,2025.000000,0.000000,2025.0,2025.0000,2025.0000,2025.0000,2025.0000
Round,25000.0,2.504880,1.118046,1.0,2.0000,3.0000,4.0000,4.0000
CoursePar,25000.0,71.333480,0.744992,70.0,71.0000,71.0000,72.0000,72.0000
DriveDistance,25000.0,295.246208,17.780500,225.0,283.2000,295.2000,307.2000,371.9000
FairwaysHit,25000.0,8.993000,2.292047,4.0,7.0000,9.0000,11.0000,14.0000
GIR,25000.0,12.012480,2.379057,6.0,10.0000,12.0000,14.0000,18.0000
Putts,25000.0,30.000040,2.588140,23.0,28.0000,30.0000,32.0000,38.0000
Birdies,25000.0,4.022440,1.976546,0.0,3.0000,4.0000,5.0000,10.0000
Bogeys,25000.0,3.000600,1.533354,0.0,2.0000,3.0000,4.0000,7.0000
Score,25000.0,71.529400,3.622703,60.0,69.0000,72.0000,74.0000,85.0000
StrokesGainedTotal,25000.0,-0.000503,1.593461,-5.0,-1.0800,-0.0000,1.0700,5.0000
Earnings,25000.0,11646.325822,6499.214142,0.0,6931.3525,11545.8550,16064.7475,35555.3500
ScoreToPar,25000.0,0.195920,3.556723,-12.0,-2.0000,0.0000,3.0000,13.0000
BirdiePct,25000.0,0.223472,0.109799,0.0,0.1667,0.2222,0.2778,0.5556
BogeyPct,25000.0,0.166708,0.085179,0.0,0.1111,0.1667,0.2222,0.3889
EarningsPerStroke,25000.0,166.986734,98.995926,0.0,94.3800,161.2950,231.2525,582.8500

#### Check Golf-Specific Ranges

Age

In [20]:
df["Age"].min(), df["Age"].max()

(18, 45)

Drive Distance

In [21]:
df["DriveDistance"].min(), df["DriveDistance"].max()

(225.0, 371.9)

Fairways Hit

In [22]:
df["FairwaysHit"].min(), df["FairwaysHit"].max()

(4, 14)

Greens in Regulation

In [24]:
df["GIR"].min(), df["GIR"].max()

(6, 18)

Putts

In [25]:
df["Putts"].min(), df["Putts"].max()

(23, 38)

Birdies

In [26]:
df["Birdies"].min(), df["Birdies"].max()

(0, 10)

Bogeys

In [ ]:
df["Bogeys"].min(), df["Bogeys"].max()

Score

In [27]:
df["Score"].min(), df["Score"].max()

(60, 85)

#### Validate Tournament Structure

In [28]:
df["Tournament"].value_counts()

Tournament
Mountain Invitational       2095
Oak Valley Open             2093
Coastal Cup                 2092
Autumn Masters              2091
Grand Lakes Championship    2088
Riverbend Open              2086
Southern Classic            2084
Cedar Hills Classic         2082
Lakeview Championship       2075
Champions Cup               2072
Highland Invitational       2071
Pine Ridge Classic          2071
Name: count, dtype: int64

In [29]:
df["Course"].value_counts()

Course
Mountain Creek             2095
Oak Valley Country Club    2093
Coastal Dunes              2092
Autumn Hills               2091
Grand Lakes Golf Club      2088
Riverbend Country Club     2086
Southern Pines             2084
Cedar Hills Golf Club      2082
Lakeview Resort            2075
Champions National         2072
Highland National          2071
Pine Ridge Golf Club       2071
Name: count, dtype: int64

In [30]:
df.groupby(["Tournament","Course"]).size()

Tournament                Course
Autumn Masters            Autumn Hills               2091
Cedar Hills Classic       Cedar Hills Golf Club      2082
Champions Cup             Champions National         2072
Coastal Cup               Coastal Dunes              2092
Grand Lakes Championship  Grand Lakes Golf Club      2088
Highland Invitational     Highland National          2071
Lakeview Championship     Lakeview Resort            2075
Mountain Invitational     Mountain Creek             2095
Oak Valley Open           Oak Valley Country Club    2093
Pine Ridge Classic        Pine Ridge Golf Club       2071
Riverbend Open            Riverbend Country Club     2086
Southern Classic          Southern Pines             2084
dtype: int64

#### Validate Round Info

In [31]:
df["Round"].min(), df["Round"].max()

(1, 4)

#### Date Validation

In [32]:
df["Date"].dtype

dtype('O')

In [33]:
df["Date"] = pd.to_datetime(df["Date"])

In [34]:
df["Date"].min(), df["Date"].max()

(Timestamp('2025-03-01 00:00:00'), Timestamp('2025-08-05 00:00:00'))

### Feature Engineering

#### Score to Par

In [35]:
df["ScoreToPar"] = df["Score"] - df["CoursePar"]

#### Birdie Percentage

In [36]:
df["BirdiePct"] = df["Birdies"] / 18

#### Bogey Percentage

In [37]:
df["BogeyPct"] = df["Bogeys"] / 18

#### Earnings per Stroke

In [38]:
df["EarningsPerStroke"] = df["Earnings"] / df["Score"]

Several derived variables were created to make the dataset more useful for
later analysis.

- **ScoreToPar** measures performance relative to the course par.
- **BirdiePct** represents birdies per hole.
- **BogeyPct** represents bogeys per hole.
- **EarningsPerStroke** provides a normalized measure of tournament earnings
  relative to the number of strokes recorded.

### Optional Attribute(s)

In [39]:
fairway_pct = (df["FairwaysHit"].mean() / 14) * 100
print("Average Fairway Percentage:", round(fairway_pct, 2), "%")

Average Fairway Percentage: 64.24 %

In [40]:
gir_pct = (df["GIR"].mean() / 18) * 100
print("Average Greens in Regulation Percentage:", round(gir_pct, 2), "%")

Average Greens in Regulation Percentage: 66.74 %

### Final Data Quality Check

In [41]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("Unique players:", df["PlayerID"].nunique())
print("Unique tournaments:", df["Tournament"].nunique())

Rows: 25000
Columns: 23
Missing values: 0
Duplicate rows: 0
Unique players: 500
Unique tournaments: 12

The final dataset contains 25,000 observations across 500 players and 12
tournaments. The dataset contains no missing values or duplicate rows.

Player identifiers were also validated to ensure that each PlayerID is
consistently associated with a single player name and that players have
multiple observations.

The dataset is now ready for exploratory analysis and subsequent project
phases.

### Export the Cleaned Dataset

In [42]:
df.to_csv("/content/drive/MyDrive/Fictional_Golf_Project/Data/Fictional_Golf_Dataset_25000_Realistic_Cleaned.csv", index=False)